# Generated by Django 4.2 on 2023-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EunoiaAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='namespace',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
