# Generated by Django 4.2 on 2023-04-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EunoiaAI', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(default=132, on_delete=django.db.models.deletion.CASCADE, to='EunoiaAI.organization'),
            preserve_default=False,
        ),
    ]
