# Generated by Django 4.2 on 2023-04-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EunoiaAI', '0004_apikey_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='secret',
        ),
    ]
