# Generated by Django 4.2 on 2023-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EunoiaAI', '0005_remove_apikey_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='primer_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
