# Generated by Django 4.2 on 2023-04-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EunoiaAI', '0006_agent_agent_name_agent_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_name',
            new_name='agent_display_name',
        ),
    ]
